version: '3'

services:
  api:
    build: .
    depends_on:
      - database
    stdin_open: true
    tty: true
    environment:
      DB_URL: 'myUrl'
      DB_NAME: 'mooc-db'
      PORT: 3000
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database:27017
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - ./:/api
  database:
    image: mongo:3.7.9
    expose:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
